### ISSUE TITLE
SecurityException for SCHEDULE_EXACT_ALARM

### ISSUE THREAD

**Issue by amirraza** [strongswan/strongswan#2125]
Following `scheduleJob` method is being invoked from JNI (as stated in inline doc) that produces a **SecurityException** on Android
https://github.com/strongswan/strongswan/blob/9d1f325a77d54d5d931aedb640a9bb87325030a8/src/frontends/android/app/src/main/java/org/strongswan/android/logic/Scheduler.java#L101

**Exception Stacktrace**
```
java.lang.SecurityException: Caller com.atom.vpn.demo needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:311)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1084)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1044)
	at android.app.AlarmManager.setExactAndAllowWhileIdle(AlarmManager.java:1312)
	at org.strongswan.android.logic.Scheduler.scheduleJob(Scheduler.kt:93)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2981)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:181)
	at android.os.Binder.execTransactInternal(Binder.java:1339)
	at android.os.Binder.execTransact(Binder.java:1275)
```

Exception is being resolved or do not produce after adding the permissions 

- `android.permission.SCHEDULE_EXACT_ALARM` 
- `android.permission.USE_EXACT_ALARM`

in `AndroidManifest.xml`. But according to the Android's official documentation, It states as 
```
Keep in mind that this is a powerful permission and app stores may enforce policies to audit and review the use of this permission. Such audits may involve removal from the app store if the app is found to be misusing this permission.
```

**Comment by amirraza** [comment]
@tobiasbrunner  the VPN application should refrain from requesting alarm permissions that require user interaction. This could potentially raise concerns about why the VPN application requires such permissions.

**Comment by tobiasbrunner** [comment]
The app requires accurate and disrupting timers (i.e. they have to trigger at an exact time even if the system tried to put the app in some kind of doze state) for NAT keepalives and other events (e.g. rekeyings). In particular for NAT keepalives connectivity from outside the NAT can't otherwise be guaranteed after a while because Android will delay regular timers etc. by up to 15 minutes after about 70 minutes of run time (could be even more restrictive nowadays, this was over 3 years ago when the new scheduler was added). That's pretty much useless for an event that has to trigger every 40 seconds, by default.
